stages:
  - test

test-default-docker:
  tags:
    - linux
  image: erlang:latest
  stage: test
  script:
    - rebar3 compile
    - rebar3 edoc
    - rebar3 dialyzer
    - rebar3 ct
  artifacts:
    when: always
    paths:
      - "_build/test/logs/last/**"
    expire_in: 3 days
    reports:
      junit:
        - _build/test/logs/last/junit_report.xml
